Lesson26
Puzinok/qna pull request #3
Opened 2017-06-22 16:46 UTC by Puzinok

2017-06-23 07:29 UTC, iBublik requested changes

2017-06-23 07:29 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
Лучше вынести это в модель пользователя, чтоб можно было делать `current_user.author_of?(@answer)`. И сверяй по id - так мы избегаем излишней загрузки модели из базы

2017-06-23 07:29 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  def set_user
А в чем смысл этого действия? `current_user` доступен нам везде, в том числе и во вьюхах

2017-06-23 07:29 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Тут аналогично ответам - `current_user.author_of?(@question)`

2017-06-23 07:29 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body).merge(user: current_user)
strong_params нужны для того, чтобы задвать список допустимых параметров, а не для того, чтобы их добавлять. Поэтому вынеси добавление current_user в create

2017-06-23 07:29 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question
Нельзя делать редирект при ошибке, т.к. в этом случае потераяется информация об ошибках и пропадет все, что вводил пользователь. Можно делать только render.

2017-06-23 07:29 UTC, iBublik commented on app/controllers/questions_controller.rb
> +      redirect_to questions_path
Нельзя делать редирект при ошибке, т.к. в этом случае потераяется информация об ошибках и пропадет все, что вводил пользователь. Можно делать только render.

2017-06-23 07:29 UTC, iBublik commented on app/controllers/answers_controller.rb
>    def new
Экшен new нам больше не нужен, т.к. форма создания ответа должна быть прямо а странице вопроса

2017-06-23 07:29 UTC, iBublik commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user == @question.user
Заметь как много дублирования этой логики. Это сигнал, что метод просто необходим. Добавь `author_of?` (название на твое усмотрение) в модель пользователя и не забудь про тесты 😉

2017-06-23 07:29 UTC, iBublik commented on app/views/questions/show.html.slim
> += form_for ([@question, @question.answers.build]) do |f|
Из-за того что ты билдишь ответ прямо во вьюхе пользователь никогда не увидит ошибки валидации

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/browse_question_and_answers_spec.rb
> +    @question = create(:valid_question)
Если переменная используется только в одном тесте, то делай ее локальной. В тестах вообще лучше не использовать инстанс переменные, лучше хелперы `let/given` - они выполняются "лениво", т.е. при первом обращении к ним. Это позволяет описывать их в шапке теста, при этом выполняться они будут только там, где нужно

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/browse_question_and_answers_spec.rb
> +    expect(page).to have_css('.answer_body', count: 3)
Пользователь видит не разметку сайта, а тексты/кнопки и прочие элементы интерфейса. Поэтому приемочные тесты нам нужно писать именно так - проверять что на странице есть ожидаемые тексты/кнопки и т.д.

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/browse_question_and_answers_spec.rb
> +feature 'Show question and answers', %q{
Нужно контексты для залогиненного/незлогиненного пользователя. Так же не хватает проверки наличия данных вопроса на странице

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/browse_questions_spec.rb
> +feature 'Browse all questions', %q{
Замечание аналогично просмотру вопроса - нужны контексты для залогиненного/незлогиненного пользователя. И проверка не по структуре страницы, а по тому что видит пользователь

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +  scenario 'User can browse question page' do
Зачем этот тетст тут? В рамках этой фичи мы должны проверить только создание вопроса пользователем

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +    User.create!(email: 'user@example.com', password: '12345678')
Для создания AR объектов у нас есть фабрики

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer the question', %q{
Не хватает тетста на создание невалидного ответа. Проверить нужно наличие ошибок валидации на странице

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Не хватает теста на создание невалидного вопроса

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/destroy_question_answer_spec.rb
> +    expect(page).to_not have_content('Delete Question')
`to have_no_button` - во-первых, лучше указывать конкретный элемент интерфейса, когда это возможно. Во-вторых, для отрицания лучше использовать встроенные в капибару матчеры (`to have_no_content` вместо `to_not_ have_content`). В них встроено ожидание, так что если элемент все же есть на страничке, капибара будет периодически проверять не исчез ли он (пока время ожидания не превысит максимально установленное). Это очень полезно на динамических страницах, где элементы скрываются через js и к тому же быстрее чем `sleep`

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/destroy_question_answer_spec.rb
> +feature 'User delete own question or answer', %q{
Неплохо проверить так же действия неавторизованного пользователя

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/sign_in_spec.rb
> +feature 'Singin in', %q{
Нужно проверить попытку входа незарегистрированного пользователя

2017-06-23 07:29 UTC, iBublik commented on spec/acceptance/sign_out_spec.rb
> +feature 'Singin out', %q{
Проверь что у залогиненного пользователя нет кнопки выхода

2017-06-23 07:29 UTC, iBublik commented on spec/factories/answers.rb
>      factory :valid_answer do
Наличие фабрики `valid_answer` мне не очень нравится - фабрика по умолчанию должна быть валидна. Для невалидных атрибутов же создается отдельная фабрика

2017-06-23 07:29 UTC, iBublik commented on spec/factories/answers.rb
> +      body "My Answer text"
Тело ответа должно быть уникально, чтоб проверить наличие всех ответов на странице пользователя - используй sequence

2017-06-23 07:29 UTC, iBublik commented on spec/factories/questions.rb
>        title "MyString"
Тело и/или заголовок вопроса должны быть уникальны, чтоб проверить наличие всех вопросов на странице пользователя - используй sequence

2017-06-23 07:29 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: user_answer } }.to change(@user.answers, :count).by(-1)
Проверяй изменение общего числа ответов - иначе тест пройдет, если мы по ошибке отвязали ответ от пользователя

2017-06-23 07:29 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
>    describe 'GET #new' do
Экшна new нам больше не требуется. А вот для create нужны контексты авторизованного/неавторизованного пользователя

2017-06-23 07:29 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Для create нужны контексты авторизованного/неавторизованного пользователя

2017-06-23 07:29 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: user_question } }.to change(@user.questions, :count).by(-1)
Нужно проверять изменение общего числа вопросов

2017-06-27 18:17 UTC, iBublik requested changes

2017-06-27 18:17 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
А почему на destroy нет авторизации?

2017-06-27 18:17 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, only: [:new, :create]
Тут тоже на destroy нужна авторизация

2017-06-27 18:17 UTC, iBublik commented on app/models/user.rb
> +    id == resource.user.id
Зачем грузить ассоциацию, когда нам нужен только id? `resource.user_id` то же самое сделает

2017-06-27 18:17 UTC, iBublik commented on app/views/questions/show.html.slim
> +  - unless answer.new_record?
Мозг легче воспринимает условия без отрицания. Поэтому я бы тут `if answer.persisted?` использовал

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/browse_question_and_answers_spec.rb
> +    expect(page).to have_content(answers.map(&:body).join)
Как-то неестественно выглядит, зачем тут все в кашу джойнится. По-моему проще в цикле проверки сделать

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/browse_questions_spec.rb
> +    expect(page).to have_content(questions.first.title)
Раз мы создали список, почему проверяем только первый вопрос?

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +  scenario "Authenticate user can answer the question" do
В этом тесте нужно так же проверить, что контент создаваемого ответа отобразился на странице

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +  scenario "Create invalid answer" do
Действия залогиненного юзера можно вынести в общий контекст и логиниться в `background` (это алиас `before` для аксептанс тестов)

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content('Errors:')
Стоит проверить конкретную ошибку валидации

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated User can create the question' do
Тут нужно проверить, что контент созданного вопроса появился на странице

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Try create invalid question' do
Рекомендация аналогично тесту на создание ответа - вынеси в контекст действия залогиненного пользователя

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/destroy_question_answer_spec.rb
> +    expect(page).to have_content('Your question succefully deleted.')
Нужно проверить, что контента вопроса больше нет на странице

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/destroy_question_answer_spec.rb
> +    expect(page).to have_content('Your answer succefully deleted.')
Нужно проверить, что контента ответа больше нет на странице

2017-06-27 18:17 UTC, iBublik commented on spec/acceptance/sign_out_spec.rb
> +feature 'Singin out', %q{
Не нашел этого теста

2017-06-27 18:17 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      render 'questions/show'
Кажется в прошлый раз я тупанул и сказал, что redirect_to нельзя делать в данном случае) Конечно можно, мы ведь тут удаляем запись, никаких ошибок валидации нет. В общем можно упростить до
```ruby
def destroy
  answer = Answer.find(params[:id])
  answer.destroy if current_user.author_of?(answer)
  redirecto_to answer.question
end
```

2017-06-27 18:17 UTC, iBublik commented on app/controllers/questions_controller.rb
> +      render :index
Тут я тоже тупанул, извиняюсь :) См. мой коммент к `AnswersController#destroy`

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +      context 'with valid attributes' do
Еще нужен тест для проверки, что ответ привязался к пользователю

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  let!(:question) { create(:question) }
А зачем тут бэнг-метод использовать?

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  let(:answer) { create(:answer, question: question) }
Не увидел для чего этот хелпер нужен

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +              user: @user
А зачем тут юзер передается?

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +            user: @user
И тут зачем?

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +          post :create, params: { answer: attributes_for(:invalid_answer), question_id: question, user: nil }
Везде какой-то лишний параметр `user`

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +      let!(:answer) { create(:answer, question: question, user: user) }
Зачем явно задавать юзера и вопрос? Фабрика сама их создаст, главное что этот созданный юзер не будет залогиненным

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +    let(:question) { create(:question, user: @user) }
А в new зачем нам вопрос? К тому же он нигде не используется

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      let(:question) { create(:question, user: @user) }
Зачем?

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +          }.to change(Question, :count).by(1)
Нужно проверить, что ответ привязался к пользователю (через ассоциацию)

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      let(:question) { create(:question) }
Зачем?

2017-06-27 18:17 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      let!(:question) { create(:question, user: user) }
Опять же, не нужно явно юзера указывать

2017-06-27 18:17 UTC, iBublik commented on spec/factories/answers.rb
> +  factory :answers, class: Answer do
А так зачем делать? Не нужно никакого "оборачивания" фабрик. Ты в итоге создал некую фабрику `answers`, которая не может сохранить объект, т.к. валидации не пройдут. Общее правило - создаешь фабрику с валидным объектом, внутри нее уже производные фабрики (невалидная сущность и т.д.). В данном случае будет так:
```ruby
factory :answer do
  sequence :body { |n| "Answer body #{n}" }
  question
  user

  factory :invalid_answer do
    body nil
    question nil
    user nil
  end
end
```

2017-06-27 18:17 UTC, iBublik commented on spec/factories/questions.rb
> +  sequence(:title) { |n| "Test title #{n}" }
В глобальном контексте объявляют только переиспользуемые последовательности (обычно в отдельном файле sequences.rb). Такие лучше в самой фабрике описывать (см. мой пример в фабрике ответа)

2017-06-27 18:17 UTC, iBublik commented on spec/factories/questions.rb
> +  factory :questions, class: Question do
См. мой коммент к фабрике ответа - не нужно изобретать вложенность

2017-06-27 18:17 UTC, iBublik commented on spec/models/user_spec.rb
> +  context '.author_of?' do
Контекст - это некий критерий, объединяющий группу тестов (действия авторизованного пользователя, например). Для описания методов используется `describe`. Инстанс-методы описываются с префиксом `#` (`descrbe '#author_of?'`), точка - обозначение методов класса

2017-06-27 18:17 UTC, iBublik commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to eq true
rspec делает динамические метчеры (методы для проверки) для методов-предикатов (это методы, которые заканчиваются на знак вопроса и возвращают true/false) и можно писать короче и красивее:
`expect(user).to be_author_of(answer)`
т.е. название метчера получается из названия метода без вопр. знака и с доавлением `be_` в начале

2017-06-29 16:14 UTC, vkurennov requested changes

2017-06-29 16:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
Не исправлено, аутентификации для destroy  по-прежнему нет

2017-06-29 16:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @answer.question, notice: 'Your answer succefully deleted.'
Но если из-за условия ответ не будет удален, сообщение все равно будет о том, что ответ успешно удален. Как-то это неправильно

2017-06-29 16:14 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, only: [:new, :create]
Да, и это по-прежнему не исправлено

2017-06-29 16:14 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path, notice: 'Your question succefully deleted.'
Опять же сообещние будет одно и то же, даже если вопрос не удален

2017-06-29 16:14 UTC, vkurennov commented on spec/acceptance/destroy_question_answer_spec.rb
> +feature 'User delete own question or answer', %q{
Фичи удаления вопроса и ответа - это 2 разные фичи, их надо разделить на 2 отдельных файла

2017-06-30 07:13 UTC, vkurennov approved these changes

2017-06-30 08:29 UTC, merged